name: orgcode
version: '0.1.0.0'
category: Web
author: Christian Fischer
maintainer: christian@chfi.se
copyright: 2017 Christian Fischer
license: BSD3
github: chfi/orgcode

extra-source-files:
- README.md

default-extensions:
- OverloadedStrings
- NoImplicitPrelude
- RecordWildCards
- DeriveFunctor

dependencies:
- protolude
- text
- bytestring
- containers
- lens
- aeson
- lens-aeson
- process
- process-extras
- directory

library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Lib
  dependencies:
  - base >=4.7 && <5

executables:
  orgcode:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - orgcode

tests:
  orgcode-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - orgcode
